<?php

namespace Afandi\BlogBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBlogPagination()
    {
        $repository = $this->getEntityManager()
            ->getRepository('AfandiBlogBundle:Blog');

        $query = $repository->createQueryBuilder('blogs')
            ->orderBy('blogs.id', 'DESC')
            ->getQuery();

        return $query;
    }
}
