<?php

namespace Afandi\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllCategoryPagination()
	{
		$repository = $this->getEntityManager()
    		->getRepository('AfandiBlogBundle:Category');
    	$query = $repository->createQueryBuilder('categories')
		    ->getQuery();

	    return $query;
	}
}
